# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3a0cee252c26af4208c60830c4ad25ceae25b9af3de196151452e99c90a58d4d82e1297bf5f69d299ae55a554df11f0d008da4eb05cbe32afea97683723053a

test:
  secret_key_base: d181fbd4fff241d20e5a8d168c22f4c503037462e241a0c08c08be9c816fa8c5ad66871dbac811a1ed495a02b4b7c57eba0ec9cafda8cfb7fe6696be82f2c7e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
